version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./db-data/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
    driver: local
    